version: '3'
services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/usr/src/app/src
    environment:
      TZ: "Europe/London"
    networks:
      - back

  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "80:80"
    volumes:
      - ./app/dist/:/var/www/html
    environment:
      TZ: "Europe/London"
    networks:
      - front
      - back

  postgresql:
    build:
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123.
      TZ: "Europe/London"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    networks:
      - back

networks:
  front:
    driver: "bridge"
  back:
    driver: "bridge"
